//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotaCorretagemMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotaCorretagemMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.NotaCorretagemMensagem", typeof(NotaCorretagemMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do pregão é obrigatória e não foi informada..
        /// </summary>
        public static string Data_Pregao_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Data_Pregao_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da nota informado é inválido..
        /// </summary>
        public static string Id_Nota_Invalido {
            get {
                return ResourceManager.GetString("Id_Nota_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nota com o ID informado não existe..
        /// </summary>
        public static string Id_Nota_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Nota_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os lançamentos da nota são obrigatórios e não foram informados..
        /// </summary>
        public static string Lancamentos_Obrigatorios_Nao_Informado {
            get {
                return ResourceManager.GetString("Lancamentos_Obrigatorios_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota de corretagem alterada com sucesso..
        /// </summary>
        public static string Nota_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Nota_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nota que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Nota_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Nota_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota de corretagem cadastrada com sucesso..
        /// </summary>
        public static string Nota_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Nota_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota de corretagem encontrada com sucesso..
        /// </summary>
        public static string Nota_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Nota_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nota não pertence ao usuário autenticado..
        /// </summary>
        public static string Nota_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Nota_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da nota é obrigatório e não foi informado..
        /// </summary>
        public static string Numero_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Numero_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Observacao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
    }
}
